In [1]:
import numpy as np
import scipy.linalg

## Урок 2. Матрицы и матричные операции

### Матрицы и матричные операции. Часть 1

#### __1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

a) A — матрица 4×2, B — матрица 4×2. Произведения матриц AB и BA не существуют, так как число строк в матрицах не совпадает с числом столбцов
б) A — матрица 2×5, B — матрица 5×3. Матрица полученая при произведении АВ будет иметь размерность 2х3. Произведения BA не существует.
в) A — матрица 8×3, B — матрица 3×8. Матрица полученая при произведении АВ будет иметь размерность 8х8. Матрица получениая при произведении ВА будет иметь размерность 3х3. 
г) A — квадратная матрица 4×4, B — квадратная матрица 4×4. Матрици полученые при произведения АВ и ВА будут иметь размерность 4х4.

#### __2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A+B=\begin{pmatrix}
1+4 & -2-1\\ 
3+0 & 0+5
\end{pmatrix}=\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}.$ <br><br>
$A*B=\begin{pmatrix}
1*4+(-2)*0 & 1*(-1)+(-2)*5\\ 
3*4+0*0 & 3*(-1)+0*5 
\end{pmatrix}=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}.$

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
A+B

array([[ 5, -3],
       [ 3,  5]])

In [3]:
A@B

array([[  4, -11],
       [ 12,  -3]])

#### _3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A=\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$ <br>
 $2B=\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$ <br> $4C=\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$ <br>
$3A-2B+4C=\begin{pmatrix}
3-0+8 & 21-10-16\\ 
9-4+4 & -18+2+4
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$ 


In [4]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
3*A-2*B+4*C

array([[ 11,  -5],
       [  9, -12]])

##### __4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$ <br><br>
$AA^{T}=\begin{pmatrix}
4*4+1*1 & 5*4+(-2)*1 & 2*4+3*1\\ 
5*4+(-2)*1 & 5*5+(-2)*(-2) & 5*2+(-2)*3\\ 
2*4+3*1 & 2*5+3*(-2) & 2*2+3*3
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$. <br><br>

$A^{T}A=\begin{pmatrix}
4*4+5*5+2*2 & 4*1+5*(-2)+2*3\\ 
1*4+(-2)*5+3*2 & 1*1+(-2)*(-2)+3*3)
\end{pmatrix} = \begin{pmatrix}
45 & 0 \\ 
0 & 14 \\
\end{pmatrix}$.

In [5]:
A = np.array([[4, 1], [5, -2], [2, 3]])
AT = A.T
AT 

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [6]:
A @ AT

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [7]:
AT @ A

array([[45,  0],
       [ 0, 14]])

### Матрицы и матричные операции. Часть 2

#### __1.__ Вычислить определитель:

a)
$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}; = sinx* sinx - (-cosx)* cosx = 1$ <br> <br>
б)
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}; = 4*5*9 = 180$<br><br>
   в)
$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1*(5*9-6*8) - 2 * (4*9 - 6*7) +  3 * (4*8-5*7) = 0 $



In [8]:
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(B)

0.0

###__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) $det(A^{2})=detA\cdot detA = 4 \cdot 4= 16 $ <br>
б) $det(A^{T}) = 4$ - так как определитель матрице не зависит будем ли мы раскладывать по сторакам или по столбцам матрицу <br>
в) $det(2A)= 2^{m} \cdot 4$ - так при умножении одной строки на число нужно умножить определитель на этой число, при умножении m строк нужно его умножить m-раз

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.


Первая и вторя строка матрицы линейно зависимы. Если две строки в матрице линейно зависимы, то её определитель равен нули и, следовательно, она является вырожденой.

##### __4.__ Найти ранг матрицы:



а) $\begin{vmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{vmatrix}; = 1*(4-3)-2(4-2)+3(3-2)=0$ <br>
Ранг матрици равен 2. <br>
б) $\begin{vmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{vmatrix} = 0 $ <br> <br>
$\begin{vmatrix}
0 & 2 & 2\\ 
0 & 4 & 3\\ 
3 & 5 & 6
\end{vmatrix} = 3*(4*6-3*5)= 27$ <br>
Ранг матрици равен 3.

In [9]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(A)

2

In [10]:
B = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 4, 5]])
np.linalg.matrix_rank(B)

3